seed: 12345
output_folder: "./delme_torino"
backend_name: "ibm_torino"      # null or "ibm_torino"
is_backend_fake: True
problem_class: "QGSProblem"
problem_params:
  num_groups: 3                 # QGSProblem
  num_instruments_per_group: 3  # QGSProblem
circuit_class: "AncillaQAOACircuit"
num_layers: 3
num_starting_points: 1
lower_bound: 0.0
upper_bound: 3.15
optimization_params:
  optimizer: "SPSA"
  tolerance: 0.1
  maxiter: 1
  learning_rate: 0.1
  perturbation: 0.1
use_cache: False
cache_filename: "delme/cache.yaml"
cache_save_every: 1
num_estimator_shots: 10000
num_sampler_shots: 100000

