seed: 12345
output_folder: N_nodes60_N_layers3_out
backend_name: ibm_torino
is_backend_fake: true
problem_class: MaxCutProblem
problem_params:
  n_nodes: 60
  density: 0.7
  num_groups: 3
  num_instruments_per_group: 3
circuit_class: QAOACircuit
num_layers: 3
num_estimator_shots: 10000
num_starting_points: 1
lower_bound: 0.0
upper_bound: 3.15
optimization_params:
  optimizer: SPSA
  tolerance: 0.1
  maxiter: 1
  learning_rate: 0.1
  perturbation: 0.1
use_cache: false
cache_filename: N_nodes60_N_layers3_out/cache.yaml
cache_save_every: 1
num_sampler_shots: 100000
only_clifford: true
